import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'hi' | 'mr';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

// Updated translations for clear, professional, and locally relatable language
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    'home': 'Home',
    'services': 'Services',
    'contact': 'Contact',
    'aboutMe': 'About Me',
    'about': 'About',
    'advocate': 'Advocate',
    'bookAppointment': 'Book Appointment',

    // Forms
    'name': 'Name',
    'email': 'Email',
    'phone': 'Phone',
    'message': 'Message',
    'submit': 'Submit',
    'fullName': 'Full Name',

    // Contact Page
    'address': 'Address',
    'callUs': 'Call Us',
    'emailUs': 'Email Us',
    'visitUs': 'Visit Us',
    'officeHours': 'Office Hours',
    'mondayToSaturday': 'Mon - Sat: 9:00 AM - 7:00 PM',
    'sunday': 'Sunday: Closed',
    'getInTouch': 'Get in Touch',
    'sendUsMessage': 'Send Us a Message',
    'scheduleAppointment': 'Book an Appointment',
    'ourLocation': 'Our Location',
    'visitOffice': 'Buddh Nagar, Indora Square, Nagpur, Maharashtra 440017',
    'convenientlyLocated': 'We are near main landmarks in Nagpur. Call us for directions if needed.',
    'connectWhatsapp': 'Connect on WhatsApp',
    'whatsappResponse': 'Message us on WhatsApp for a quick reply during office hours.',
    'connectOnWhatsapp': 'WhatsApp Me',

    // Services Page
    'ourLegalServices': 'Our Legal Services',
    'experienceTagline': 'With 12+ years of experience, we offer simple and effective legal help for your needs. See our services below.',
    'civilLaw': 'Civil Law',
    'criminalLaw': 'Criminal Law',
    'familyLaw': 'Family Law',
    'propertyDocumentation': 'Property & Documents',
    'consumerProtection': 'Consumer Protection',
    'ourLegalProcess': 'Our Legal Process',
    'processTagline': 'We follow a step-by-step process to solve your legal problems.',
    'initialConsultation': 'First Meeting',
    'consultationDesc': 'We talk about your case and understand your needs.',
    'caseAnalysis': 'Case Check',
    'analysisDesc': 'We look at your situation and plan the best way forward.',
    'legalRepresentation': 'Legal Support',
    'representationDesc': 'We speak for you in court or with others.',
    'resolution': 'Solution',
    'resolutionDesc': 'We work for the best result for you.',
    'readyForSupport': 'Need Legal Help?',
    'scheduleConsultation': 'Book a meeting with Adv. Jasvinder Singh Ply to discuss your legal needs.',
    'bookConsultation': 'Book Consultation',

    // Home Page
    'aboutTagline': 'About',
    'expYears': '12+ years in law',
    'aboutDesc1': 'Adv. Jasvinder Singh Ply has 12 years of experience helping people in Nagpur with civil, criminal, and family law.',
    'aboutDesc2': 'He works with honesty and gives personal attention to every client. You get clear advice and friendly support.',
    'aboutDesc3': 'No matter your legal problem, Adv. Singh is here to guide you and find the best solution.',
    'scheduleCons': 'Book a Meeting',
    'servicesPreview': 'Our Services',
    'servicesPreviewDesc': 'We offer a range of legal services for your needs. Our team gives you personal solutions.',
    'viewAllServices': 'See All Services',
    'whyChooseUs': 'Why Choose Us',
    'expLegalExpertise': 'Experienced Lawyer',
    'expLegalDesc': 'With 12+ years in law, we know how to handle your case.',
    'personalizedApproach': 'Personal Care',
    'personalizedDesc': 'Every client is different, so we give you the right advice for your situation.',
    'clearCommunication': 'Simple Communication',
    'clearCommDesc': 'We explain everything in easy words.',
    'accessibility': 'Easy to Reach',
    'accessibilityDesc': 'We answer your questions and help you at every step.',
    'clientTestimonials': 'Client Feedback',
    'testimonial1': '"Adv. Jasvinder handled my property case very well. I am happy with his work."',
    'testimonial1Author': '- Rajesh Kumar, Nagpur',
    'testimonial2': '"He paid attention to my case and solved it quickly. I recommend him."',
    'testimonial2Author': '- Priya Sharma, Nagpur',
    'needLegal': 'Need Legal Help?',
    'needLegalDesc': 'If you have a legal problem or need advice, our team is ready to help.',
    'learnMoreServices': 'Learn More About Our Services',

    // Footer
    'contactUs': 'Contact Us',
    'quickLinks': 'Quick Links',
    'practiceAreas': 'Practice Areas',
    'allRightsReserved': 'All rights reserved.',
    'legalExcellence': 'Years of Legal Excellence',

    // Service descriptions
    'civilRights': 'Civil Rights Cases',
    'civilRightsDesc': 'Help in cases about your rights and protection.',
    'disabilityBenefits': 'Disability Benefits',
    'disabilityDesc': 'Help with accident claims and getting compensation.',
    'evictionLitigation': 'Eviction Cases',
    'evictionDesc': 'Support for landlords or tenants in eviction matters.',
    'landlordTenant': 'Landlord-Tenant Cases',
    'landlordDesc': 'Solve problems between landlords and tenants.',
    'recoverySuit': 'Recovery Case',
    'recoveryDesc': 'Get back your money or property through court.',
    'criminalWrit': 'Criminal Writ',
    'criminalWritDesc': 'File petitions for relief in criminal matters.',
    'regularBail': 'Regular Bail',
    'regularBailDesc': 'Get bail after arrest.',
    'anticipatoryBail': 'Anticipatory Bail',
    'anticipatoryDesc': 'Apply for bail before arrest.',
    'chequeBouncing': 'Cheque Bounce Cases',
    'chequeDesc': 'Help in cheque bounce matters.',
    'domesticViolence': 'Domestic Violence',
    'domesticDesc': 'Support and protection for victims.',
    'mutualDivorce': 'Mutual Divorce',
    'mutualDesc': 'Help with divorce when both agree.',
    'divorce': 'Divorce',
    'divorceDesc': 'Support in contested divorce cases.',
    'registerMarriage': 'Marriage Registration',
    'marriageDesc': 'Legal help for marriage registration.',
    'willWriting': 'Will Writing',
    'willDesc': 'Write your will for property distribution.',
    'partnershipDeed': 'Partnership Registration',
    'partnershipDesc': 'Prepare and register business partnership.',
    'legalNotice': 'Legal Notice',
    'noticeDesc': 'Send formal legal notices for you.',
    'propertyRegistry': 'Property Registry',
    'registryDesc': 'Manage paperwork for property sale or transfer.',
    'propertyDisputes': 'Property Disputes',
    'disputesDesc': 'Solve property ownership or boundary issues.',
    'agreements': 'Agreements',
    'agreementsDesc': 'Draft and review legal agreements.',
    'consumerComplaint': 'Consumer Complaint',
    'consumerDesc': 'Help in complaints about products or services.'
  },
  hi: {
    // Navbar
    'home': 'होम', // Use 'होम' for homepage in Hindi websites[5]
    'services': 'सेवाएं',
    'contact': 'संपर्क',
    'aboutMe': 'मेरे बारे में',
    'about': 'बारे में',
    'advocate': 'वकील',
    'bookAppointment': 'अपॉइंटमेंट बुक करें',

    // Forms
    'name': 'नाम',
    'email': 'ईमेल',
    'phone': 'फोन',
    'message': 'संदेश',
    'submit': 'सबमिट करें',
    'fullName': 'पूरा नाम',

    // Contact Page
    'address': 'पता',
    'callUs': 'कॉल करें',
    'emailUs': 'ईमेल करें',
    'visitUs': 'आइए मिलें',
    'officeHours': 'कार्यालय समय',
    'mondayToSaturday': 'सोम-शनि: सुबह 9 - शाम 7',
    'sunday': 'रविवार: बंद',
    'getInTouch': 'संपर्क करें',
    'sendUsMessage': 'संदेश भेजें',
    'scheduleAppointment': 'अपॉइंटमेंट बुक करें',
    'ourLocation': 'हमारा पता',
    'visitOffice': 'बुद्ध नगर, इंदोरा चौक, नागपुर, महाराष्ट्र 440017',
    'convenientlyLocated': 'हम नागपुर के मुख्य स्थानों के पास हैं। रास्ता पूछना हो तो कॉल करें।',
    'connectWhatsapp': 'व्हाट्सएप पर जुड़ें',
    'whatsappResponse': 'जल्दी जवाब के लिए व्हाट्सएप करें (ऑफिस समय में)।',
    'connectOnWhatsapp': 'व्हाट्सएप करें',

    // Services Page
    'ourLegalServices': 'हमारी कानूनी सेवाएं',
    'experienceTagline': '12+ साल के अनुभव के साथ, हम आपकी जरूरतों के लिए आसान और असरदार कानूनी मदद देते हैं।',
    'civilLaw': 'सिविल कानून',
    'criminalLaw': 'आपराधिक कानून',
    'familyLaw': 'पारिवारिक कानून',
    'propertyDocumentation': 'संपत्ति और दस्तावेज',
    'consumerProtection': 'उपभोक्ता संरक्षण',
    'ourLegalProcess': 'हमारी कानूनी प्रक्रिया',
    'processTagline': 'हम आपकी समस्या सुलझाने के लिए आसान तरीका अपनाते हैं।',
    'initialConsultation': 'पहली मुलाकात',
    'consultationDesc': 'आपका केस समझते हैं और सलाह देते हैं।',
    'caseAnalysis': 'केस देखना',
    'analysisDesc': 'स्थिति देखकर सही रास्ता बताते हैं।',
    'legalRepresentation': 'कानूनी मदद',
    'representationDesc': 'कोर्ट या बाहर आपकी तरफ से बोलते हैं।',
    'resolution': 'समाधान',
    'resolutionDesc': 'आपके लिए अच्छा हल निकालते हैं।',
    'readyForSupport': 'कानूनी मदद चाहिए?',
    'scheduleConsultation': 'अपॉइंटमेंट बुक करें और अपनी बात रखें।',
    'bookConsultation': 'अपॉइंटमेंट बुक करें',

    // Home Page
    'aboutTagline': 'परिचय',
    'expYears': '12+ साल का अनुभव',
    'aboutDesc1': 'अधिवक्ता जसविंदर सिंह प्लाय ने 12 साल से नागपुर में लोगों की मदद की है।',
    'aboutDesc2': 'ईमानदारी और व्यक्तिगत ध्यान के साथ हर केस को देखते हैं।',
    'aboutDesc3': 'कोई भी कानूनी समस्या हो, हम आपके साथ हैं।',
    'scheduleCons': 'मुलाकात बुक करें',
    'servicesPreview': 'हमारी सेवाएं',
    'servicesPreviewDesc': 'हम आपकी जरूरतों के लिए अलग-अलग कानूनी सेवाएं देते हैं।',
    'viewAllServices': 'सभी सेवाएं देखें',
    'whyChooseUs': 'हमें क्यों चुनें',
    'expLegalExpertise': 'अनुभवी वकील',
    'expLegalDesc': '12+ साल का अनुभव, हर केस में सही सलाह।',
    'personalizedApproach': 'व्यक्तिगत ध्यान',
    'personalizedDesc': 'हर ग्राहक के लिए अलग सलाह।',
    'clearCommunication': 'आसान भाषा',
    'clearCommDesc': 'हर बात साफ-साफ समझाते हैं।',
    'accessibility': 'आसान संपर्क',
    'accessibilityDesc': 'हर सवाल का जवाब मिलता है।',
    'clientTestimonials': 'ग्राहक अनुभव',
    'testimonial1': '"मेरा प्रॉपर्टी केस अच्छे से सुलझाया। बहुत संतुष्ट हूँ।"',
    'testimonial1Author': '- राजेश कुमार, नागपुर',
    'testimonial2': '"मेरे केस पर ध्यान दिया और जल्दी हल किया। जरूर सलाह दूंगा।"',
    'testimonial2Author': '- प्रिया शर्मा, नागपुर',
    'needLegal': 'कानूनी मदद चाहिए?',
    'needLegalDesc': 'कोई भी कानूनी परेशानी हो, हम आपकी मदद के लिए तैयार हैं।',
    'learnMoreServices': 'हमारी सेवाओं के बारे में जानें',

    // Footer
    'contactUs': 'संपर्क करें',
    'quickLinks': 'जरूरी लिंक',
    'practiceAreas': 'सेवा क्षेत्र',
    'allRightsReserved': 'सर्वाधिकार सुरक्षित।',
    'legalExcellence': 'कानूनी अनुभव',

    // Service descriptions
    'civilRights': 'नागरिक अधिकार केस',
    'civilRightsDesc': 'आपके अधिकारों की रक्षा के लिए मदद।',
    'disabilityBenefits': 'अपंगता लाभ',
    'disabilityDesc': 'दुर्घटना या मुआवजे के लिए सहायता।',
    'evictionLitigation': 'बेदखली केस',
    'evictionDesc': 'मकान मालिक या किरायेदार के लिए मदद।',
    'landlordTenant': 'मकान मालिक-किरायेदार केस',
    'landlordDesc': 'मकान या किराए के झगड़े सुलझाएं।',
    'recoverySuit': 'वसूली केस',
    'recoveryDesc': 'पैसे या संपत्ति वापस दिलवाएं।',
    'criminalWrit': 'आपराधिक रिट',
    'criminalWritDesc': 'आपराधिक मामलों में याचिका लगाएं।',
    'regularBail': 'नियमित जमानत',
    'regularBailDesc': 'गिरफ्तारी के बाद जमानत दिलवाएं।',
    'anticipatoryBail': 'अग्रिम जमानत',
    'anticipatoryDesc': 'गिरफ्तारी से पहले जमानत के लिए आवेदन।',
    'chequeBouncing': 'चेक बाउंस केस',
    'chequeDesc': 'चेक बाउंस मामलों में मदद।',
    'domesticViolence': 'घरेलू हिंसा',
    'domesticDesc': 'पीड़ितों को सुरक्षा और मदद।',
    'mutualDivorce': 'आपसी तलाक',
    'mutualDesc': 'दोनों की सहमति से तलाक में मदद।',
    'divorce': 'तलाक',
    'divorceDesc': 'झगड़े वाले तलाक मामलों में मदद।',
    'registerMarriage': 'विवाह रजिस्ट्रेशन',
    'marriageDesc': 'शादी रजिस्ट्रेशन में कानूनी मदद।',
    'willWriting': 'वसीयत बनवाना',
    'willDesc': 'संपत्ति बांटने की वसीयत तैयार करें।',
    'partnershipDeed': 'साझेदारी रजिस्ट्रेशन',
    'partnershipDesc': 'व्यापार साझेदारी के कागज बनवाएं।',
    'legalNotice': 'कानूनी नोटिस',
    'noticeDesc': 'आपके लिए कानूनी नोटिस भेजें।',
    'propertyRegistry': 'संपत्ति रजिस्ट्री',
    'registryDesc': 'संपत्ति खरीद-बिक्री के कागज बनवाएं।',
    'propertyDisputes': 'संपत्ति विवाद',
    'disputesDesc': 'संपत्ति के झगड़े सुलझाएं।',
    'agreements': 'समझौते',
    'agreementsDesc': 'कानूनी समझौते तैयार करें।',
    'consumerComplaint': 'उपभोक्ता शिकायत',
    'consumerDesc': 'प्रोडक्ट या सर्विस की शिकायत में मदद।'
  },
  mr: {
    // Navbar
    'home': 'होम', // Use 'होम' for homepage in Marathi as well for clarity
    'services': 'सेवा',
    'contact': 'संपर्क',
    'aboutMe': 'माझ्याविषयी',
    'about': 'बद्दल',
    'advocate': 'वकील',
    'bookAppointment': 'अपॉइंटमेंट बुक करा',

    // Forms
    'name': 'नाव',
    'email': 'ईमेल',
    'phone': 'फोन',
    'message': 'संदेश',
    'submit': 'सबमिट करा',
    'fullName': 'पूर्ण नाव',

    // Contact Page
    'address': 'पत्ता',
    'callUs': 'कॉल करा',
    'emailUs': 'ईमेल करा',
    'visitUs': 'भेट द्या',
    'officeHours': 'कार्यालय वेळ',
    'mondayToSaturday': 'सोम-शनि: सकाळी 9 - संध्याकाळी 7',
    'sunday': 'रविवार: बंद',
    'getInTouch': 'संपर्क करा',
    'sendUsMessage': 'संदेश पाठवा',
    'scheduleAppointment': 'अपॉइंटमेंट बुक करा',
    'ourLocation': 'आमचा पत्ता',
    'visitOffice': 'बुद्ध नगर, इंदोरा चौक, नागपूर, महाराष्ट्र 440017',
    'convenientlyLocated': 'आम्ही नागपूरच्या मुख्य ठिकाणी आहोत. मार्गदर्शन हवे असल्यास कॉल करा.',
    'connectWhatsapp': 'व्हॉट्सअ‍ॅपवर संपर्क करा',
    'whatsappResponse': 'जलद उत्तरासाठी व्हॉट्सअ‍ॅपवर मेसेज करा (ऑफिस वेळेत).',
    'connectOnWhatsapp': 'व्हॉट्सअ‍ॅप करा',

    // Services Page
    'ourLegalServices': 'आमच्या कायदेशीर सेवा',
    'experienceTagline': '12+ वर्षांचा अनुभव, सोप्या भाषेत आणि योग्य कायदेशीर मदत.',
    'civilLaw': 'नागरी कायदा',
    'criminalLaw': 'फौजदारी कायदा',
    'familyLaw': 'कौटुंबिक कायदा',
    'propertyDocumentation': 'मालमत्ता व कागदपत्रे',
    'consumerProtection': 'ग्राहक संरक्षण',
    'ourLegalProcess': 'आमची कायदेशीर प्रक्रिया',
    'processTagline': 'आम्ही तुमच्या समस्येचे सोपे समाधान देतो.',
    'initialConsultation': 'पहिली भेट',
    'consultationDesc': 'तुमच्या प्रकरणाबद्दल बोलतो आणि समजून घेतो.',
    'caseAnalysis': 'केस तपासणी',
    'analysisDesc': 'स्थिती पाहून योग्य सल्ला देतो.',
    'legalRepresentation': 'कायदेशीर मदत',
    'representationDesc': 'कोर्टात किंवा इतरत्र तुमची बाजू मांडतो.',
    'resolution': 'समाधान',
    'resolutionDesc': 'तुमच्यासाठी चांगला निकाल मिळवतो.',
    'readyForSupport': 'कायदेशीर मदत हवी आहे का?',
    'scheduleConsultation': 'अपॉइंटमेंट बुक करा आणि समस्या सांगा.',
    'bookConsultation': 'अपॉइंटमेंट बुक करा',

    // Home Page
    'aboutTagline': 'परिचय',
    'expYears': '12+ वर्षांचा अनुभव',
    'aboutDesc1': 'अॅड. जसविंदर सिंह प्लाय यांनी 12 वर्षांपासून नागपूरमध्ये लोकांना मदत केली आहे.',
    'aboutDesc2': 'प्रामाणिकपणे आणि प्रत्येक क्लायंटला वैयक्तिक लक्ष देऊन काम करतात.',
    'aboutDesc3': 'कोणतीही कायदेशीर अडचण असो, आम्ही तुमच्या सोबत आहोत.',
    'scheduleCons': 'भेट बुक करा',
    'servicesPreview': 'आमच्या सेवा',
    'servicesPreviewDesc': 'तुमच्या गरजांसाठी वेगवेगळ्या कायदेशीर सेवा देतो.',
    'viewAllServices': 'सर्व सेवा पहा',
    'whyChooseUs': 'आम्हाला का निवडावे',
    'expLegalExpertise': 'अनुभवी वकील',
    'expLegalDesc': '12+ वर्षांचा अनुभव, प्रत्येक प्रकरणात योग्य मार्गदर्शन.',
    'personalizedApproach': 'वैयक्तिक लक्ष',
    'personalizedDesc': 'प्रत्येकासाठी वेगळी सल्ला.',
    'clearCommunication': 'सोप्या भाषेत संवाद',
    'clearCommDesc': 'प्रत्येक गोष्ट साध्या शब्दात समजावतो.',
    'accessibility': 'सोपे संपर्क',
    'accessibilityDesc': 'प्रत्येक प्रश्नाला उत्तर मिळते.',
    'clientTestimonials': 'ग्राहक अनुभव',
    'testimonial1': '"माझ्या प्रॉपर्टी प्रकरणात चांगली मदत झाली. समाधानी आहे."',
    'testimonial1Author': '- राजेश कुमार, नागपूर',
    'testimonial2': '"माझ्या प्रकरणावर लक्ष दिले आणि लवकर निकाल दिला. नक्कीच शिफारस करतो."',
    'testimonial2Author': '- प्रिया शर्मा, नागपूर',
    'needLegal': 'कायदेशीर मदत हवी आहे का?',
    'needLegalDesc': 'कायदेशीर अडचण असल्यास, आम्ही मदतीसाठी तयार आहोत.',
    'learnMoreServices': 'आमच्या सेवांबद्दल जाणून घ्या',

    // Footer
    'contactUs': 'संपर्क करा',
    'quickLinks': 'महत्वाचे लिंक्स',
    'practiceAreas': 'सेवा क्षेत्र',
    'allRightsReserved': 'सर्व हक्क राखीव.',
    'legalExcellence': 'कायदेशीर अनुभव',

    // Service descriptions
    'civilRights': 'नागरी हक्क प्रकरण',
    'civilRightsDesc': 'तुमच्या हक्कांसाठी मदत.',
    'disabilityBenefits': 'अपंगत्व लाभ',
    'disabilityDesc': 'अपघात किंवा भरपाईसाठी मदत.',
    'evictionLitigation': 'बेदखली प्रकरण',
    'evictionDesc': 'मालक किंवा भाडेकरूसाठी मदत.',
    'landlordTenant': 'मालक-भाडेकरू प्रकरण',
    'landlordDesc': 'मालमत्ता किंवा भाड्याचे वाद सोडवा.',
    'recoverySuit': 'वसुली प्रकरण',
    'recoveryDesc': 'पैसे किंवा मालमत्ता परत मिळवा.',
    'criminalWrit': 'फौजदारी रिट',
    'criminalWritDesc': 'फौजदारी प्रकरणात अर्ज करा.',
    'regularBail': 'नियमित जामीन',
    'regularBailDesc': 'अटक झाल्यावर जामीन मिळवा.',
    'anticipatoryBail': 'पूर्व-जामीन',
    'anticipatoryDesc': 'अटक होण्यापूर्वी जामीन मिळवा.',
    'chequeBouncing': 'चेक बाउन्स प्रकरण',
    'chequeDesc': 'चेक बाउन्स प्रकरणात मदत.',
    'domesticViolence': 'घरगुती हिंसा',
    'domesticDesc': 'पीडितांना मदत आणि सुरक्षा.',
    'mutualDivorce': 'परस्पर संमतीने घटस्फोट',
    'mutualDesc': 'दोघांच्या संमतीने घटस्फोटात मदत.',
    'divorce': 'घटस्फोट',
    'divorceDesc': 'वादग्रस्त घटस्फोट प्रकरणात मदत.',
    'registerMarriage': 'विवाह नोंदणी',
    'marriageDesc': 'शादी नोंदणीसाठी मदत.',
    'willWriting': 'मृत्युपत्र तयार करणे',
    'willDesc': 'मालमत्ता वाटपासाठी मृत्युपत्र तयार करा.',
    'partnershipDeed': 'भागीदारी नोंदणी',
    'partnershipDesc': 'व्यवसाय भागीदारीचे कागद बनवा.',
    'legalNotice': 'कायदेशीर नोटीस',
    'noticeDesc': 'तुमच्या वतीने नोटीस पाठवा.',
    'propertyRegistry': 'मालमत्ता नोंदणी',
    'registryDesc': 'मालमत्ता विक्री किंवा हस्तांतरणासाठी कागद तयार करा.',
    'propertyDisputes': 'मालमत्ता वाद',
    'disputesDesc': 'मालकी किंवा सीमा वाद सोडवा.',
    'agreements': 'करार',
    'agreementsDesc': 'कायदेशीर करार तयार करा.',
    'consumerComplaint': 'ग्राहक तक्रार',
    'consumerDesc': 'प्रॉडक्ट किंवा सेवेसाठी तक्रारीत मदत.'
  }
};

export const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('language');
    return (savedLanguage as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
