// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqcafjbmeqmfzctwroee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxY2FmamJtZXFtZnpjdHdyb2VlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMDEwMTYsImV4cCI6MjA2MTY3NzAxNn0.UO4J0bgGjsLS9DcmOM1x1-Ny37dEzHs5ze_Pe7qn3ow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);